<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.9" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.9" />
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="FluentValidation" Version="12.0.0" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
		<PackageReference Include="MediatR" Version="13.0.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
		<PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
		<PackageReference Include="Serilog.Enrichers.Process" Version="3.0.0" />
		<PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
		<PackageReference Include="Serilog.Sinks.Seq" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Behaviour\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Evently.Common.Domain\Evently.Common.Domain.csproj" />
	</ItemGroup>
	
</Project>
